// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package order

import (
	"github.com/adnanahmady/go-grpc-microservices/config"
	"github.com/adnanahmady/go-grpc-microservices/pkg/applog"
	"github.com/adnanahmady/go-grpc-microservices/pkg/request"
)

// Injectors from wire.go:

func InitService(serviceName string) (*OrderService, error) {
	configConfig := config.GetConfig()
	appLogger := applog.NewAppLogger(configConfig, serviceName)
	userServiceClient, err := ConnectToUserService(configConfig)
	if err != nil {
		return nil, err
	}
	inventoryServiceClient, err := ConnectToInventoryService(configConfig)
	if err != nil {
		return nil, err
	}
	server := NewServer(userServiceClient, inventoryServiceClient)
	middlewares := request.NewMiddlewares(appLogger, configConfig)
	orderService := &OrderService{
		Config:      configConfig,
		Logger:      appLogger,
		Server:      server,
		Middlewares: middlewares,
	}
	return orderService, nil
}
