// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/adnanahmady/go-grpc-microservices/config"
	"github.com/adnanahmady/go-grpc-microservices/pkg/applog"
	"github.com/adnanahmady/go-grpc-microservices/pkg/request"
)

// Injectors from wire.go:

func InitService(serviceName string) (*UserService, error) {
	configConfig := config.GetConfig()
	appLogger := applog.NewAppLogger(configConfig, serviceName)
	server := NewServer()
	middlewares := request.NewMiddlewares(appLogger, configConfig)
	userService := &UserService{
		Config:      configConfig,
		Logger:      appLogger,
		Server:      server,
		Middlewares: middlewares,
	}
	return userService, nil
}
